package ml.codevilla.springboot.student;
/*Create StudentRepository Interface
    [23]-Extend JpaRepository<Student, Long> :
        if using CrudRepository, extend that and pass arguments
        @Repository
    [24]-to use functions of JPA:
        Create reference of Repo in Service class
        dependency inject the instance studentRepository
        ->go to StudentService.
    [44]-use @Query annotation to specify SQL query otherwise:
        it is also auto-generated by JpQL for us when we name method as findStudentByEmail
        go to -> StudentService Class

 */
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.Optional;

@Repository
public interface StudentRepository extends JpaRepository<Student, Long> {

    @Query("SELECT s FROM Student s WHERE s.email=?1")
    Optional<Student> findStudentByEmail(String email);
}
